### ISSUE TITLE
Release plan for pre-trained models

### ISSUE THREAD

**Issue by MRzNone** [penn-pal-lab/peg#1]
Is there a plan to release pre-trained models? It will greatly help my research. Thank you very much for the great work.

**Comment by edwhu** [comment]
Hi, there is currently no plan, but I can work on that. Unfortunately, our cluster's filesystem is down, and it has all the experiment checkpoint.

Just letting you know, each experiment runs in 1 day on 1 GPU and 4 cpus so it shouldn't be hard to train your own.

**Comment by MRzNone** [comment]
It would be great if a release is possible.

I am currently training the three stack task and the point maze task, on my machine. The three stack task, on step 762,000, seems to struggle to stack cubes. I will wait for the training to finish. But, pre-trained models could greatly help the process. Thank you very much.

I am running with the `peg_three_stack` config.

eval_gc_policy (on step 762,000)
![individualImage](https://github.com/penn-pal-lab/peg/assets/8140868/c433621b-3cb8-4fdf-9f3a-e79bb9deeffa)

**Comment by edwhu** [comment]
The hardest stack has high seed variance, so you will need to run multiple seeds (I ran 5 in my paper). Some will not learn at all.

I can give you the weights from my cluster, it will take me some effort to get them (few days). Thank you for your patience.

**Comment by MRzNone** [comment]
I see. Thank you for your quick response. I'll put my machines to work while waiting for your weights. Thank you very much.

**Comment by edwhu** [comment]
Closed, issue was because the block stacking env was not updated.
