### ISSUE TITLE
Some variable names and functions are missing

### ISSUE THREAD

**Issue by IDayday** [penn-pal-lab/peg#3]
When I follow the tutorial and try to train the PEG, I get some problems.
I can start normally in a complete conda environment, and all dependencies can be configured. 
I try :
```
python examples/run_goal_cond.py --configs peg_point_maze
```
But some names of class are wrong, I checkout the source in project [mrl](https://github.com/edwhu/mrl) on branch master.
is "PointMaze2D" not "MultiGoalPointMaze2D"
```
# i.e., run_goal_cond.py
from envs.sibrivalry.toy_maze import MultiGoalPointMaze2D
```
and some functions may not be defined. 
* no env.render() in pointmaze 
* no env.get_goals() in pointmaze and antmaze
```
# i.e., run_goal_cond.py   
  elif 'pointmaze' in config.task:
    Pointmaze and MEGA envs define a goal distribution, so we sample from it for eval.
    def episode_render_fn(env, ep):
      all_img = []
      goals = []
      executions = []
      inner_env = env._env._env._env._env
      inner_env.g_xy = ep['goal'][0]
      inner_env.s_xy = ep['goal'][0]
      goal_img = env.render()
      for xy in ep['observation']:
        inner_env.s_xy = xy
        img = env.render()
        all_img.append(img)
      env.clear_plots()
      goals.append(goal_img[None]) # 1 x H x W x C
      ep_img = np.stack(all_img, 0)
      # pad if episode length is shorter than time limit.
      T = ep_img.shape[0]
      ep_img = np.pad(ep_img, ((0, (config.time_limit+1) - T), (0,0), (0,0), (0,0)), 'constant', constant_values=(0))
      executions.append(ep_img[None]) # 1 x T x H x W x C
      return goals, executions
```
So, can you provide a correct version?

**Comment by edwhu** [comment]
Hi, I checked the master branch of `mrl`, and see MultiGoalPointMaze2D defined here.

https://github.com/edwhu/mrl/blob/4f1ab3930519c3d372654dbfcde2b821f7fd8439/envs/sibrivalry/toy_maze/__init__.py#L238

env.render and env.get_goals should work for MultiGoalPointMaze2D since you can see the functions defined there. 

Please let me know if something is not running.

**Comment by IDayday** [comment]
sry, I confused "spitis/mrl" and "edwhu/mrl", thank you for your prompt feedback.
