### ISSUE TITLE
Visual Tasks latent space

### ISSUE THREAD

**Issue by Alvin-pc** [penn-pal-lab/peg#6]
Can this code be used for dmc_walker_walk_visual task? Evaluation goals are already specified in lexa-benchmark!
I can see that the file in example can create the env for dmc_walker_walk_visual , but can the training be done for the same? I suppose setting cnn keys would it?

Also did you run peg on dmc_walker_walk_visual? Any results?

**Comment by edwhu** [comment]
PEG only supports state-based tasks, so no.
An image-based extension would be quite straightforward, we just need to sample goals in the latent space of the image.  See  https://github.com/penn-pal-lab/peg/issues/2#issuecomment-1804510955

**Comment by Alvin-pc** [comment]
> No, we did not test in Atari envs. It should be possible to extend PEG to Atari though, but goal generation would need to be done in some latent space, like [Director.](https://danijar.com/project/director/)

I beleive you are saying that a goal autoencoder needs to be used like in Director. But in PEG, since it is using dreamer_v2, the world model also uses discrete codes of the latent state. So doesn't that mean I can generate goals directly in this space?

**Comment by edwhu** [comment]
Yes, the discrete codes could be an option. I think it might better to generate goals in the embed space (deterministic output of the CNN / MLP of the observation), as seen from LEXA and Director.

**Comment by Alvin-pc** [comment]
I am able to run LEXA for visual walker using your code. Since the sampling is done randomly from the replay buffer, i dont think it uses embed space for goals.
```
def get_goal(self, obs):
    random_batch = next(self._dataset)
    random_batch = self.wm.preprocess(random_batch)
    random_goals = tf.reshape(random_batch[self.state_key], (-1,) + tuple(random_batch[self.state_key].shape[2:]))
    return random_goals[:obs[self.state_key].shape[0]]
```
Now for PEG, i was able to run search_goal partly, but I am not sure **how the goal in the embed space(1024) can be brought back to 64X64X3**. My understanding is that the **decoder can only generate goal image using state['feat'] = [stoch,deter].** But we are only optimising over goals in the embed space. The mean and sigma are embed_size dimensional.

```
def search_goal(self, obs, state=None, mode='train'):
    /Code to update goal distribution
    goal= self.sample_goal()
    return goal
```
This returning goal is (1024). But search_goal has to return a state or image(64X64X3)!

**Comment by Alvin-pc** [comment]
An alternate approach I am thinking of is to use the **goal in embed form throughout the GC Driver**. That way I dont need to concern myself with decoding the goal image.

**Comment by edwhu** [comment]
Conceptually, there is no need to decode the goal embedding, since the goal embedding is just the encoded form of the goal observation. If you have the goal embedding already, you can just feed that to the policy. 

You will need to change the codebase a little to support this, but I think it makes sense to avoid decoding the embedding.

**Comment by edwhu** [comment]
PEG was developed in low dimensional MDPs (which still are hard exploration MDPS), so that's why we optimized in the input space.

**Comment by Alvin-pc** [comment]
Thank you. Not decoding the goal embedding works just fine.
